server:
  port: 9091
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true
    service-url:
      deafultZone: http://localhost:8761/eureka
